version: "3.10"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pokemon-datavolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: .
    command: uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/code
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - MY_ALGORITHMS=${MY_ALGORITHMS}
      - SECRET=${SECRET}
    depends_on:
      - db

volumes:
  pokemon-datavolume: